package com.amirrezahadipoor.herodefense.gameplay;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.amirrezahadipoor.herodefense.items.EquipmentCatalog;
import com.amirrezahadipoor.herodefense.model.ItemTier;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import org.junit.jupiter.api.Test;

/**
 * The drop economy's table, generated from the code that rolls it (roadmap R4.3, first half).
 *
 * <p>Rates, pool sizes and sell prices live in three places — {@code ItemDropSystem}, {@code EquipmentCatalog} and
 * {@code EquipmentDefinition} — and a document that copies them lies the first time one of them moves. This test
 * computes the table from the same constants the game rolls and asserts that the block published in
 * {@code docs/BALANCE.md} is exactly what it computed, so the numbers are checked rather than trusted. The same file
 * records the three pity rules that were measured against the balance sweep and blocked: they are candidates with
 * prices, not behaviour, and the tests that would hold a shipped rule are written when one can pass.
 */
final class DropEconomyTableTest {
    private static final float TOTAL_RATE = 0.099515f;

    private final ItemDropSystem drops = new ItemDropSystem();

    @Test
    void thePublishedDropTableIsWhatTheCodeSays() {
        Path document = balanceDocument();
        String published = read(document);
        String rates = generatedRateTable();
        assertTrue(published.contains(rates),
            "the drop table in " + document + " is not what the code computes. Regenerated block:\n" + rates);
    }

    @Test
    void theItemBudgetAndItsCoinValueAddUp() {
        float items = 0f;
        float coins = 0f;
        for (ItemTier tier : ItemTier.values()) {
            items += baseRate(tier);
            coins += baseRate(tier) * sellPrice(tier);
        }
        assertEquals(TOTAL_RATE, items, 1e-6f, "about one item per ten kills");
        assertEquals(2.49591f, coins, 1e-4f, "and about two and a half coins per kill");
    }

    @Test
    void theTierBandsAreCumulativeAndLuckStretchesThem() {
        assertNull(drops.tierForRoll(TOTAL_RATE, 1f), "the budget runs out at 9.9515 percent");
        assertEquals(ItemTier.COMMON, drops.tierForRoll(TOTAL_RATE, 2f), "Luck buys longer bands");
        assertEquals(ItemTier.MYTHIC, drops.tierForRoll(0f, 1f));
        assertEquals(ItemTier.LEGENDARY, drops.tierForRoll(0.0001f, 1f), "under 0.0015 percent");
        assertEquals(ItemTier.RARE, drops.tierForRoll(0.005f, 1f), "under 0.0095");
        assertEquals(ItemTier.UNCOMMON, drops.tierForRoll(0.02f, 1f), "under 0.0395");
        assertEquals(ItemTier.COMMON, drops.tierForRoll(0.09f, 1f), "under 0.0995");
    }

    @Test
    void everyTierStillHasAPoolToPickFrom() {
        for (ItemTier tier : ItemTier.values()) {
            int pool = poolSize(tier);
            assertTrue(pool > 0, tier + " has no equipment, so a roll in its band would have nothing to drop");
        }
        assertEquals(46, EquipmentCatalog.all().size(), "the shipped pool, so a content edit has to say so here");
    }

    private String generatedRateTable() {
        List<String> lines = new ArrayList<>();
        lines.add("<!-- generated by DropEconomyTableTest: edit the code, not this table -->");
        lines.add("| tier | rate per kill | share of the item budget | pool | sell price | coins per kill |");
        lines.add("|---|---|---|---|---|---|");
        float items = 0f;
        float coins = 0f;
        for (ItemTier tier : ItemTier.values()) {
            float rate = baseRate(tier);
            items += rate;
            coins += rate * sellPrice(tier);
            lines.add(String.format(Locale.ROOT, "| `%s` | %.4f%% | %.2f%% | %d | %d | %.4f |",
                tier, rate * 100f, rate / TOTAL_RATE * 100f, poolSize(tier), sellPrice(tier), rate * sellPrice(tier)));
        }
        lines.add(String.format(Locale.ROOT, "| **total** | %.4f%% | 100%% | %d | | **%.4f** |",
            items * 100f, EquipmentCatalog.all().size(), coins));
        return String.join("\n", lines) + "\n";
    }

    private static int poolSize(ItemTier tier) {
        return (int) EquipmentCatalog.all().stream().filter(item -> item.tier() == tier).count();
    }

    private static float baseRate(ItemTier tier) {
        return switch (tier) {
            case COMMON -> ItemDropSystem.COMMON_RATE;
            case UNCOMMON -> ItemDropSystem.UNCOMMON_RATE;
            case RARE -> ItemDropSystem.RARE_RATE;
            case LEGENDARY -> ItemDropSystem.LEGENDARY_RATE;
            case MYTHIC -> ItemDropSystem.LEGENDARY_RATE * ItemDropSystem.MYTHIC_SHARE_OF_LEGENDARY;
        };
    }

    private static int sellPrice(ItemTier tier) {
        return EquipmentCatalog.all().stream()
            .filter(item -> item.tier() == tier)
            .findFirst()
            .orElseThrow()
            .createItem()
            .sellPrice;
    }

    /** Gradle runs the core module's tests from its own directory, so the document is one level up. */
    private static Path balanceDocument() {
        Path fromModule = Path.of("docs", "BALANCE.md");
        return Files.exists(fromModule) ? fromModule : Path.of("..", "docs", "BALANCE.md");
    }

    private static String read(Path path) {
        try {
            return Files.readString(path);
        } catch (java.io.IOException error) {
            throw new IllegalStateException("cannot read " + path, error);
        }
    }
}
