#!/usr/bin/env python3
"""Print the generated performance page and check it against the logged runs (roadmap R8.5).

The rule this enforces: a performance number in this repository's documentation comes from a logged run,
never from memory. `docs/perf/runs/*.json` holds the runs; `docs/perf/PERFORMANCE.md` is *generated* from
them, so `--check` failing means somebody edited the page by hand instead of logging a run.

Usage:
    python3 tools/perf/render_performance_doc.py            # print the page
    python3 tools/perf/render_performance_doc.py --check    # exit 1 if docs/perf/PERFORMANCE.md differs
    python3 tools/perf/render_performance_doc.py --write    # (re)generate the page
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PERF = ROOT / "docs" / "perf"
RUNS = PERF / "runs"
PAGE = PERF / "PERFORMANCE.md"
BUDGETS = ("apk_budget.json", "startup_budget.json", "wave50_memory_budget.json")
HEADER = (
    "# Performance\n\n"
    "Generated by `tools/perf/render_performance_doc.py` from `docs/perf/runs/*.json` and the budget files\n"
    "next to it. Do not edit this page: log a run instead (`docs/perf/README.md`). Every number below can be\n"
    "traced to the commit and the command that produced it.\n"
)


def load_runs() -> list[dict]:
    if not RUNS.is_dir():
        return []
    runs = []
    for path in sorted(RUNS.glob("*.json")):
        runs.append(json.loads(path.read_text()))
    return runs


def load_budgets() -> dict[str, dict]:
    budgets = {}
    for name in BUDGETS:
        path = PERF / name
        if path.is_file():
            budgets[name] = json.loads(path.read_text())
    return budgets


def render(runs: list[dict], budgets: dict[str, dict]) -> str:
    out = [HEADER]
    out.append("## Metrics and where they come from\n\n")
    out.append("| Metric | Value | Unit | Run | Commit | Measured by |\n|---|---:|---|---|---|---|\n")
    for run in runs:
        for metric in run["metrics"]:
            out.append(
                "| `{name}` | {value} | {unit} | `{run_id}` ({date}) | `{commit}` | `{command}` |\n".format(
                    name=metric["name"],
                    value=metric["value"],
                    unit=metric["unit"],
                    run_id=run["id"],
                    date=run["date"],
                    commit=run["commit"],
                    command=run["command"],
                )
            )
    out.append("\n## Budgets the build enforces\n\n")
    out.append("| Budget | Threshold | Unit | Enforced by |\n|---|---:|---|---|\n")
    for name, budget in sorted(budgets.items()):
        for key, value in sorted(budget["thresholds"].items()):
            out.append(
                "| `{key}` | {value} | {unit} | `{enforced}` |\n".format(
                    key=key,
                    value=value,
                    unit=budget.get("unit", ""),
                    enforced=budget["enforced_by"],
                )
            )
    out.append("\n## Runs\n\n")
    for run in runs:
        out.append(
            "- `{id}` — {date}, `{commit}`. {note}\n".format(
                id=run["id"], date=run["date"], commit=run["commit"], note=run.get("note", "")
            )
        )
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the committed page is stale")
    parser.add_argument("--write", action="store_true", help="write the page")
    args = parser.parse_args()

    page = render(load_runs(), load_budgets())
    if args.write:
        PAGE.write_text(page)
        print(f"wrote {PAGE.relative_to(ROOT)}")
        return 0
    if args.check:
        committed = PAGE.read_text() if PAGE.is_file() else ""
        if committed != page:
            print("docs/perf/PERFORMANCE.md is not what the runs say; run --write or log a run")
            sys.stdout.write(page)
            return 1
        print("performance page matches the logged runs")
        return 0
    sys.stdout.write(page)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
