package com.amirrezahadipoor.herodefense.balance;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/**
 * {@code docs/BALANCE.md} cannot drift from the code (roadmap R4.4).
 *
 * <p>The document carries numbers a player-facing balance claim rests on, and every one of them used to be typed by
 * hand: the wave-100 health checkpoint was two curve revisions stale when this test was written, and the quarter
 * means in the R4.6 table had been copied out of a terminal. Now the blocks that consist of numbers are generated by
 * {@link BalanceDocument} from the same constants and the same simulator the game runs, they are fenced in the
 * document by {@code balance:generated} markers, and this test fails when the file disagrees with the code — naming
 * the block, and telling the reader to run {@code :core:regenerateBalanceDoc} rather than to hand-edit.
 *
 * <p>What stays authored is the prose: the reasoning, the rejected candidates, the history. That is the split the
 * markers draw, and the second test here keeps the split honest by refusing a block marker the code does not own.
 *
 * <p>Tagged {@code balance} because generating the blocks runs the sweep: this is the gate's work, and it runs in
 * the gate's job.
 */
@Tag("balance")
final class BalanceDocumentTest {

    @Test
    void everyGeneratedBlockIsWhatTheCodeComputes() {
        String document = read(BalanceDocument.locate());
        List<String> drifted = BalanceDocument.driftedBlocks(document);
        if (drifted.isEmpty()) {
            assertEquals(BalanceDocument.BLOCKS.size(), countGeneratedBlocks(document),
                "every block in the document must carry its markers");
            return;
        }
        String first = drifted.get(0);
        fail("docs/BALANCE.md disagrees with the code in " + drifted
            + ". The code says " + first + " is now:\n" + BalanceDocument.block(first)
            + "\nRun `./gradlew :core:regenerateBalanceDoc` to rewrite the generated blocks.");
    }

    @Test
    void theDocumentOnlyClaimsBlocksTheGeneratorOwns() {
        String document = read(BalanceDocument.locate());
        for (String block : BalanceDocument.BLOCKS) {
            assertEquals(1, occurrences(document, BalanceDocument.open(block)),
                "block " + block + " must have exactly one opening marker");
            assertEquals(1, occurrences(document, BalanceDocument.close(block)),
                "block " + block + " must have exactly one closing marker");
            assertTrue(document.indexOf(BalanceDocument.open(block)) < document.indexOf(BalanceDocument.close(block)),
                "block " + block + "'s markers must open before they close");
        }
        assertEquals(BalanceDocument.BLOCKS.size(), occurrences(document, "<!-- balance:generated "),
            "the document carries a generated block the code does not own: every block has to be in "
                + BalanceDocument.BLOCKS);
        assertEquals(BalanceDocument.BLOCKS.size(), occurrences(document, "<!-- balance:end "),
            "the document carries an end marker the code does not own");
    }

    private static int countGeneratedBlocks(String document) {
        return occurrences(document, "<!-- balance:generated ");
    }

    private static int occurrences(String text, String needle) {
        int count = 0;
        int from = 0;
        while (true) {
            int index = text.indexOf(needle, from);
            if (index < 0) {
                return count;
            }
            count++;
            from = index + needle.length();
        }
    }

    private static String read(java.nio.file.Path path) {
        try {
            return Files.readString(path, StandardCharsets.UTF_8);
        } catch (IOException error) {
            throw new UncheckedIOException(error);
        }
    }
}
