#!/usr/bin/env python3
"""Write the shaping vectors the Persian shaper is held to (roadmap R7.3).

The game draws text with a bitmap font, and a bitmap font has no shaper: libGDX rasterises the codepoints it
is given, in the order it is given them. Persian needs both halves of that solved -- every letter takes one of
four forms depending on its neighbours, and the run is written right to left while the digits and Latin words
inside it stay left to right.

`core/src/main/java/.../render/PersianShaper.java` does that in the game, in pure Java. This tool is how the
repository knows it is right: it asks two libraries this repository did not write -- `arabic_reshaper` for the
contextual forms and `python-bidi` for the reordering -- to shape the same corpus, and writes their answers
into `golden/shaping-vectors.txt`. `PersianShaperTest` then asserts the Java shaper reproduces every vector,
codepoint for codepoint.

That is the same shape of evidence as the ETC2 encoder being held to Google's reference blocks: the
implementation is ours, the expectation is not.

Usage:
    python3 tools/i18n/make_shaping_vectors.py           # write the golden file
    python3 tools/i18n/make_shaping_vectors.py --check   # fail if the golden file is not what the reference says

The reference libraries are pinned by version below, because the golden file is a statement about *their*
output: if a library changes what it produces, `--check` fails and the change is a decision, not a surprise.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import unicodedata

HERE = pathlib.Path(__file__).resolve().parent
GOLDEN = HERE / "golden" / "shaping-vectors.txt"

# The versions the committed golden file was generated with. `--check` refuses to compare against anything
# else, so an upgraded library cannot quietly redefine what "correctly shaped" means.
REFERENCE_VERSIONS = {
    "arabic-reshaper": "3.0.1",
    "python-bidi": "0.6.11",
}

HEADER = """# Persian shaping vectors, generated by tools/i18n/make_shaping_vectors.py -- do not edit by hand.
#
# Each line is: <logical text> TAB <visual codepoints, hex, space separated>.
# "Logical" is what the string table says; "visual" is what a left-to-right bitmap font must be handed for the
# eye to read it as Persian. Produced by arabic_reshaper {reshaper} + python-bidi {bidi} on CPython {python}
# with Unicode {unicode}.
#
# The Java shaper (render/PersianShaper.java) has to reproduce every line. PersianShaperTest fails on the first
# one it does not, printing both sides as codepoints.
"""

PERSIAN_LETTERS = (
    "آاآبپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیئءةی"
)

# Words the game actually puts on screen, in the two locales' shared vocabulary. Nothing here is decorative:
# a vector that no shipped string resembles would prove the shaper works on text the game never says.
UI_STRINGS = (
    "بازی جدید",
    "ادامه",
    "تنظیمات",
    "شبکه ریشه",
    "کدکس بیشه",
    "پاسداری کوتاه",
    "دفاع از قهرمان",
    "درخت جهان در انتظار است",
    "آخرین پناهگاه سبز را نگه دارید",
    "یک دور کامل در سی موج",
    "بازگشت به موج جاری",
    "چوب دل و رشد دائمی",
    "راحتی، موسیقی و جلوه‌ها",
    "گزینه‌های راحتی روی این دستگاه ذخیره می‌شوند",
    "جلوه‌های صوتی",
    "ضربه‌ها، غنیمت‌ها و ارتقای سطح",
    "موسیقی",
    "قطعهٔ پاسداری درخت جهان",
    "سطح جلوه‌ها",
    "تیرها، ضربه‌ها و غنیمت",
    "سطح موسیقی",
    "بلندی صدای پاسداری",
    "فقط لمسی",
    "برای تغییر یک ردیف را لمس کنید",
    "برای بازگشت به منوی اصلی دکمهٔ بستن را لمس کنید",
    "زبان",
    "انگلیسی",
    "فارسی",
    "مکث",
    "ادامهٔ بازی",
    "ترک کردن",
    "شکست خوردید",
    "درخت سوخت",
    "موج بعدی",
    "یک کارت انتخاب کنید",
    "سطح بالاتر رفت",
    "پیش‌نویس آزمون",
    "کیسهٔ پشت",
    "فروشگاه",
    "بستن",
    "خرید",
    "فروش",
    "تجهیز",
    "برداشتن",
    "سکه",
    "جان",
    "آسیب",
    "سرعت",
    "شانس",
    "گریز",
    "دل",
)


def corpus() -> list[str]:
    """Every case the shaper has to get right, in an order that puts the mechanics first."""
    cases: list[str] = []

    # 1. Each letter on its own: the isolated form, and the proof that a letter with no medial form (ا د ر ز
    #    ژ و) never invents one.
    cases.extend(letter for letter in PERSIAN_LETTERS)

    # 2. Each letter between two dual-joining carriers: the medial form.
    cases.extend(f"ب{letter}ب" for letter in PERSIAN_LETTERS)

    # 3. Each letter leading and trailing: the initial and final forms.
    cases.extend(f"{letter}ب" for letter in PERSIAN_LETTERS)
    cases.extend(f"ب{letter}" for letter in PERSIAN_LETTERS)

    # 4. The lam-alef ligature, which is mandatory rather than decorative, in both of its forms and with each
    #    of the alefs that can carry a hamza.
    cases.extend(["لا", "لأ", "لإ", "لآ", "سلام", "بلا", "الله", "الا", "کلاه"])

    # 5. The zero-width non-joiner, which Persian needs the way English needs a space: می‌رود is one word and
    #    two joins that must not happen.
    cases.extend(["می‌رود", "خانه‌ها", "بازی‌ها", "سیب‌زمینی", "به‌هم", "‌", "ب‌ب"])

    # 6. The zero-width joiner, and the tatweel, which stretches a join without adding a letter.
    cases.extend(["ب‍ب", "بـب", "ـ", "بـ"])

    # 7. Harakat, which the reference deletes: a vowel mark is not a letter and must not become a join.
    cases.extend(["بَ", "بِ", "بُ", "بً", "بٍ", "بٌ", "بّ", "بْ", "مُحمَّد"])

    # 8. Numbers and Latin inside a Persian sentence. This is where a naive shaper breaks: the digits stay in
    #    their own order while the words around them reverse.
    cases.extend([
        "موج ۱۴۰",
        "۲۰۰ موج یا سی",
        "سطح ۵",
        "۵۰٪",
        "HP ۵۰",
        "Wave 140",
        "موج 140",
        "۰۱۲۳۴۵۶۷۸۹",
        "۱۲۳ بازی ۴۵۶",
        "Tier 3 | Peak 175 | 42 HW",
    ])

    # 9. Punctuation, which belongs to the run it sits in: the Persian comma and question mark are not the
    #    ASCII ones, and a full stop between two Persian words reverses with them.
    cases.extend(["بازی جدید؟", "بله، ادامه", "نه!", "سلام.", "«درخت»", "(موج)", "الف؛ب"])

    # 10. The empty and the already-shaped: shaping must be safe to call on anything the table holds.
    cases.extend(["", " ", "  ", "\u200f", "\u200e"])

    # 11. Everything the game says.
    cases.extend(UI_STRINGS)

    seen: set[str] = set()
    unique = [case for case in cases if not (case in seen or seen.add(case))]
    return unique


def shape(text: str) -> str:
    """The reference answer: contextual forms, then visual order."""
    import arabic_reshaper
    from bidi.algorithm import get_display

    return get_display(arabic_reshaper.reshape(text))


def versions() -> dict[str, str]:
    from importlib import metadata

    return {name: metadata.version(name) for name in REFERENCE_VERSIONS}


def render() -> str:
    found = versions()
    for name, want in REFERENCE_VERSIONS.items():
        got = found.get(name)
        if got != want:
            raise SystemExit(
                f"{name} is {got}, the golden vectors were generated with {want}. "
                "Re-run without --check only if the difference has been looked at."
            )

    lines = [HEADER.format(
        reshaper=found["arabic-reshaper"],
        bidi=found["python-bidi"],
        # The interpreter is named by minor version and by the Unicode data it carries, because those are the
        # two things that could change an answer: python-bidi asks unicodedata for each character's bidi class
        # and its mirrored pair, and that table is a property of the CPython minor, not of its patch level. A
        # patch release cannot drift this file, so recording one only ever made `--check` fail on a machine
        # that was equally right. CI pins this minor with actions/setup-python for the same reason.
        python=".".join(str(part) for part in sys.version_info[:2]),
        unicode=unicodedata.unidata_version,
    ).rstrip("\n")]
    for case in corpus():
        visual = shape(case)
        hexed = " ".join(f"{ord(character):04X}" for character in visual)
        one_line = case.replace("\n", "\\n").replace("\t", "\\t")
        lines.append(f"{one_line}\t{hexed}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail instead of writing")
    parser.add_argument("--count", action="store_true", help="print the corpus size and stop")
    arguments = parser.parse_args()

    if arguments.count:
        print(f"{len(corpus())} vectors")
        return 0

    produced = render()
    if arguments.check:
        if not GOLDEN.is_file():
            print(f"MISSING {GOLDEN}")
            return 2
        committed = GOLDEN.read_text(encoding="utf-8")
        if committed != produced:
            print(f"DRIFT {GOLDEN}: the reference no longer produces the committed vectors")
            print(f"  committed lines: {len(committed.splitlines())}")
            print(f"  generated lines: {len(produced.splitlines())}")
            for index, (was, now) in enumerate(
                zip(committed.splitlines(), produced.splitlines())
            ):
                if was != now:
                    print(f"  first difference at line {index + 1}")
                    print(f"    committed: {was[:160]}")
                    print(f"    generated: {now[:160]}")
                    break
            return 2
        print(f"OK {GOLDEN} matches arabic_reshaper + python-bidi on {len(corpus())} vectors")
        return 0

    GOLDEN.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN.write_text(produced, encoding="utf-8")
    print(f"wrote {GOLDEN} ({len(corpus())} vectors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
