#!/usr/bin/env python3
"""Compose the runtime tier out of the genuine master renders (roadmap R5.2).

Why this exists: the Blender batch at `6449a6d` rendered the premium characters onto 384 px frames (a
3840x1536 sheet, one bounded page). Phase 78 then composed the *reviewed* runtime tier by halving those
renders onto 192 px frames, because the catalog ceiling of the day could not hold the full-resolution tier --
and the halving is what the runtime has shipped since. R5.2 is the other direction: for the sheets whose
pixels the provenance measurement calls an *independent render* rather than an enlarged copy, ship the render
itself instead of half of it.

Selection is measured, never listed here. A sheet is composed when both of these hold:

* the master batch's own manifest (`--master-commit`) declares it at 384 px frames on a 3840x1536 sheet, and
* `docs/art_reviews/MASTER_TIER_PROVENANCE.md` -- generated by `tools/visual/classify_master_tier.py` from
  fine-detail and correlation measurements against the reviewed baseline -- classifies it as an independent
  render. `hero_ceremony` is a resampled copy and the world trees and `void_knight` are inconclusive, so the
  same rule that selects eight sheets also *excludes* five that sit at the same resolution, which is the point:
  shipping a render is a claim, and the claim is measured.

What it does per selected sheet, in one pass so nothing can describe geometry the pixels do not have:

* copies the master's pixels byte for byte out of the master commit's tree -- the shipped sheet *is* the
  render, with no resampling step to audit;
* re-derives the frame rectangles with `plan_grid` at 384 px frames and refuses to continue unless they equal
  the master manifest's own rectangles exactly, and unless the page is the single page the atlas contract
  allows;
* rewrites the libGDX atlas text, the per-asset sidecar and the manifest entry together, stamps the reviewed
  pivot for the asset's frame class, and records the render facts in `masterRender` with `lod: none`;
* recomputes the catalog's decoded bytes the way the runtime counts them -- every sheet plus every icon
  the manifest names -- and regenerates `docs/asset_hashes.json`, the ledger `AssetIntegrityTest` checks;
* sets the page ceiling to the atlas contract's 4096 -- while the
  owner's decision on the catalog and combat budgets stays what it is in the manifest, because a tool does not
  get to change a budget silently.

    python3 tools/visual/compose_master_tier.py --check      # the working tree is a rebuild of this
    python3 tools/visual/compose_master_tier.py --write      # compose and stamp
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import subprocess
import sys
from pathlib import Path

from PIL import Image

REPOSITORY = Path(__file__).resolve().parents[2]
VISUAL = Path(__file__).resolve().parent
sys.path.insert(0, str(VISUAL))
sys.path.insert(0, str(REPOSITORY / "tools" / "blender"))

from hd_pipeline.atlas_layout import MAX_ATLAS_SIZE, plan_grid  # noqa: E402
from repack_committed_assets import PIVOTS, _write_atlas  # noqa: E402  (the shipping metaball contract)

#: The render batch the genuine masters come from, and the file that classifies them.
MASTER_COMMIT = "6449a6d"
PROVENANCE_DOCUMENT = REPOSITORY / "docs" / "art_reviews" / "MASTER_TIER_PROVENANCE.md"
#: The render batch's own line, recorded beside the pixels it produced.
MASTER_ENGINE_VERSION = "73.0-studio-v5-hd-pbr-4x48-pbr"
MASTER_FRAME_SIZE = 384
MASTER_VISUAL_QUALITY = "studio-v5-hd-pbr"
CLIP_ORDER = ("idle", "attack", "hit", "death")
#: The committed hash ledger every PNG is pinned by, and the date this composition stamps into it.
HASH_LEDGER = "docs/asset_hashes.json"
COMPOSED_ON = "2026-09-17"


def _run(*args: str) -> bytes:
    """Read a blob out of the repository's history, and say why if this clone cannot reach it.

    The composition is defined against the render batch's own manifest -- "the master render's geometry" is a
    fact about a commit, not about today's tree -- so this check needs the history that commit lives in. CI
    checked out one commit and the check died inside `subprocess` with nothing a reader could act on, so the
    failure is named here: a shallow checkout is the one thing that breaks this, and `fetch-depth: 0` is the
    fix.
    """
    result = subprocess.run(["git", *args], cwd=REPOSITORY, capture_output=True, check=False)
    if result.returncode != 0:
        detail = result.stderr.decode("utf-8", "ignore").strip().splitlines()
        raise SystemExit(
            "git " + " ".join(args) + " failed -- " + (detail[-1] if detail else "no output")
            + ". This tool reads the manifest as the render batch committed it (" + MASTER_COMMIT + "), so"
              " the clone has to carry that commit: a shallow checkout is not enough. In a workflow that means"
              " `actions/checkout` with `fetch-depth: 0`."
        )
    return result.stdout


def master_manifest() -> dict:
    return json.loads(_run("show", f"{MASTER_COMMIT}:android/assets/generated/asset_manifest.json"))


def master_sheet_bytes(sheet: str) -> bytes:
    return _run("show", f"{MASTER_COMMIT}:android/assets/generated/{sheet}")


def independent_renders() -> set[str]:
    """The sheets the provenance measurement calls independent renders, read from its own table."""
    classified: set[str] = set()
    section = ""
    for line in PROVENANCE_DOCUMENT.read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            section = line[3:].split(" \u2014")[0].split(" - ")[0].strip()
        match = re.match(r"\| `([^`]+)` \|", line)
        if match and section.startswith("Independent renders"):
            classified.add(match.group(1))
    if not classified:
        raise SystemExit(f"no independent renders found in {PROVENANCE_DOCUMENT}")
    return classified


def selected_keys(manifest: dict) -> list[str]:
    """The sheets to compose: at 384 px frames in the master batch *and* measured as genuine renders."""
    classified = independent_renders()
    keys = []
    for entry in master_manifest()["assets"]:
        sheet = entry.get("sheet") or ""
        if not sheet.startswith("sprites/"):
            continue
        if entry.get("frameSize") != MASTER_FRAME_SIZE:
            continue
        if (entry.get("sheetWidth"), entry.get("sheetHeight")) != (3840, 1536):
            continue
        if sheet not in classified:
            continue
        keys.append(entry["key"])
    if not keys:
        raise SystemExit("nothing to compose: the master batch and the provenance document disagree")
    return sorted(keys)


def composed_assets(root: Path) -> dict[str, dict]:
    """The sheets the manifest should carry at the master's own resolution, keyed by asset key."""
    master = master_manifest()
    by_key = {entry["key"]: entry for entry in master["assets"]}
    manifest = json.loads((root / "asset_manifest.json").read_text(encoding="utf-8"))
    current = {entry["key"]: entry for entry in manifest["assets"]}
    result: dict[str, dict] = {}
    for key in selected_keys(manifest):
        master_entry = by_key[key]
        asset = json.loads(json.dumps(current[key]))       # a copy, never the committed object
        counts = {clip: len(asset["clips"][clip]) for clip in CLIP_ORDER}
        pages, regions = plan_grid(counts, MASTER_FRAME_SIZE)
        if len(pages) != 1:
            raise SystemExit(f"{key}: composing at 384 px needs {len(pages)} atlas pages, not one")
        page = pages[0]
        if (page["width"], page["height"]) != (master_entry["sheetWidth"], master_entry["sheetHeight"]):
            raise SystemExit(f"{key}: planned page {page} is not the master's own sheet")
        for clip, frames in regions.items():
            mine = sorted((f["x"], f["y"], f["width"], f["height"], f["index"]) for f in frames)
            theirs = sorted(
                (f["x"], f["y"], f["width"], f["height"], f["index"]) for f in master_entry["clips"][clip]
            )
            if mine != theirs:
                raise SystemExit(f"{key}/{clip}: planned rectangles are not the master manifest's rectangles")
        asset["frameSize"] = MASTER_FRAME_SIZE
        asset["clips"] = {clip: regions[clip] for clip in CLIP_ORDER}
        asset["sheetWidth"] = page["width"]
        asset["sheetHeight"] = page["height"]
        asset["sheets"] = [
            {
                "file": asset["sheet"],
                "width": page["width"],
                "height": page["height"],
                "decodedBytes": page["width"] * page["height"] * 4,
            }
        ]
        x, y = PIVOTS[asset["frameClass"]]
        asset["pivot"] = {"x": x, "y": y, "units": "normalized-bottom-left"}
        asset["alphaMode"] = "STRAIGHT_RGBA"
        asset["visualQuality"] = MASTER_VISUAL_QUALITY
        asset["masterRender"] = {
            "engineVersion": master_entry.get("engineVersion", MASTER_ENGINE_VERSION),
            "frameSize": MASTER_FRAME_SIZE,
            "lod": "none -- the shipped sheet is the master's own render",
            "materialCount": master_entry.get("materialCount"),
            "masterCommit": MASTER_COMMIT,
            "meshParts": master_entry.get("meshParts"),
            "renderSamples": master_entry.get("renderSamples"),
            "renderSupersample": master_entry.get("renderSupersample"),
            "sheetHeight": page["height"],
            "sheetWidth": page["width"],
        }
        result[key] = asset
    return result


def compose(root: Path) -> dict[str, bytes]:
    """Every file the composed tier consists of, so a rebuild can be compared byte for byte."""
    manifest = json.loads((root / "asset_manifest.json").read_text(encoding="utf-8"))
    composed = composed_assets(root)
    files: dict[str, bytes] = {}
    for key, asset in composed.items():
        files[asset["sheet"]] = master_sheet_bytes(asset["sheet"])
    for entry in manifest["assets"]:
        key = entry["key"]
        if key in composed:
            entry.clear()
            entry.update(composed[key])
    manifest["maxAtlasPageSize"] = MAX_ATLAS_SIZE
    manifest["masterTier"] = {
        "engineVersion": MASTER_ENGINE_VERSION,
        "evidence": "docs/art_reviews/MASTER_TIER_PROVENANCE.md",
        "frameSize": MASTER_FRAME_SIZE,
        "masterCommit": MASTER_COMMIT,
        "note": (
            "Eight sprite sheets ship the render batch's own pixels at 384 px frames instead of a halved copy "
            "of them, because the provenance measurement classifies those eight as independent renders and "
            "everything else at that resolution as a resampled copy or inconclusive. The catalog ceiling and "
            "the combat residency budget are the manifest's business, not this tool's."
        ),
        "sheets": sorted(composed),
    }
    # The catalog's decoded total counts what the runtime counts -- every sheet in the manifest plus every
    # icon the manifest names -- and it is measured from the composed pixels rather than summed from the old
    # numbers, so the figure cannot drift away from the bytes.
    manifest["decodedBytes"] = _decoded_total(files, root, manifest)
    files["asset_manifest.json"] = _json_bytes(manifest)
    for key, asset in composed.items():
        files[_sidecar_path(asset)] = _json_bytes(asset)
        files[asset["atlas"]] = _atlas_text(asset)
    files[HASH_LEDGER] = _ledger(files, root, manifest)
    return files


def _composed_or_committed(files: dict[str, bytes], root: Path, relative: str) -> bytes:
    """The pixel bytes of a sheet: the composed ones where there are any, what is committed otherwise."""
    return files.get(relative) or (root / relative).read_bytes()


def _icon_files(asset: dict) -> list[str]:
    return [asset["icon"]] if asset.get("icon") else []


def _decoded_total(files: dict[str, bytes], root: Path, manifest: dict) -> int:
    total = 0
    for asset in manifest["assets"]:
        for relative in [sheet["file"] for sheet in asset.get("sheets", [])] + _icon_files(asset):
            with Image.open(io.BytesIO(_composed_or_committed(files, root, relative))) as image:
                total += image.size[0] * image.size[1] * 4
    return total


def _ledger(files: dict[str, bytes], root: Path, manifest: dict) -> bytes:
    """The committed ledger, regenerated from the composed pixels so it can never describe another tree."""
    ledger = json.loads((REPOSITORY / HASH_LEDGER).read_text(encoding="utf-8"))
    ledger["generatedAt"] = COMPOSED_ON
    for asset in manifest["assets"]:
        for relative in [sheet["file"] for sheet in asset.get("sheets", [])] + _icon_files(asset):
            ledger["sheets"][relative] = hashlib.sha256(
                _composed_or_committed(files, root, relative)
            ).hexdigest()
    return _json_bytes(ledger)


def _sidecar_path(asset: dict) -> str:
    family = asset["family"]
    if family in {"hero", "enemy", "boss", "world_tree"}:
        return f"sprites/{asset['key']}.json"
    if family == "equipment":
        return f"equipment/{asset['itemId']}.json"
    return f"{family}/{asset['key']}.json"


def _atlas_text(asset: dict) -> bytes:
    lines = [
        Path(asset["sheet"]).name,
        f"size: {asset['sheetWidth']},{asset['sheetHeight']}",
        "format: RGBA8888",
        "filter: Nearest,Nearest",
        "repeat: none",
    ]
    for clip in CLIP_ORDER:
        for frame in sorted(asset["clips"][clip], key=lambda item: item["index"]):
            lines += [
                f"{asset['key']}_{clip}",
                "  rotate: false",
                f"  xy: {frame['x']}, {frame['y']}",
                f"  size: {frame['width']}, {frame['height']}",
                f"  orig: {frame['width']}, {frame['height']}",
                "  offset: 0, 0",
                f"  index: {frame['index']}",
            ]
    return ("\n".join(lines) + "\n").encode("utf-8")


def _json_bytes(value: object) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")


def _output_path(root: Path, name: str) -> Path:
    """Assets live under the generated root; the hash ledger lives beside the reviews, not inside them."""
    return REPOSITORY / name if name == HASH_LEDGER else root / name


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=REPOSITORY / "android" / "assets" / "generated")
    parser.add_argument("--write", action="store_true", help="write the composed tier into the assets")
    parser.add_argument("--check", action="store_true", help="fail unless the assets are this composition")
    args = parser.parse_args()
    root = args.root.resolve()
    files = compose(root)
    composed = composed_assets(root)
    if args.write:
        for name, blob in files.items():
            _output_path(root, name).write_bytes(blob)
            print(f"wrote {name} ({len(blob)} bytes)")
    if args.check:
        drifted = [
            name for name, blob in files.items()
            if not _output_path(root, name).exists() or _output_path(root, name).read_bytes() != blob
        ]
        if drifted:
            print("the composed tier is not what is committed: " + ", ".join(sorted(drifted)))
            return 1
    sheets = sorted(composed)
    total = sum(asset["sheets"][0]["decodedBytes"] for asset in composed.values())
    print(f"composed {len(sheets)} sheets at {MASTER_FRAME_SIZE} px frames: {', '.join(sheets)}")
    print(f"their decoded bytes: {total} ({total / (1024 * 1024):.1f} MiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
