#!/usr/bin/env python3
"""Audit and render exhaustive review evidence for the four premium-v2 bosses."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from PIL import Image, ImageDraw

from create_character_animation_review import (
    CLIP_ORDER,
    CharacterFrames,
    canvas_base,
    create_motion_sheet,
    create_readability_sheet,
    presentation_card,
    text,
)

from review_strips import grade_row

import master_tier

# Studio-v3 contact-sheet mode: same side-by-side-against-baseline layout as premium-v2,
# baseline is the current premium-v2 output, candidate is studio-v3 (weighted 2.4/1.2 + rim/highlight).
STUDIO_TIER_BASELINE_QUALITY = "premium-v2"
STUDIO_TIER_CANDIDATE_QUALITY = "studio-v3"
# Contact sheet uses readability_sheet(old, new) with old=premium-v2, new=studio-v3


BOSSES = (
    ("ancient_golem", "Ancient Golem", "heartstone-colossus-v2", "premium-heavy-humanoid-v2", "ancient-golem-ground-slam-v2"),
    ("thorn_matriarch", "Thorn Matriarch", "briar-sovereign-v2", "premium-rooted-caster-v2", "thorn-matriarch-thorn-cage-v2"),
    ("ember_wyrm", "Ember Wyrm", "furnace-wyrm-v2", "premium-winged-wyrm-mapped-v2", "ember-wyrm-flame-sweep-v2"),
    ("void_knight", "Void Knight", "abyss-champion-v2", "premium-armored-humanoid-v2", "void-knight-void-charge-v2"),
)
SIGNATURE_ATTACKS = {
    "ancient_golem": "ground_slam",
    "thorn_matriarch": "thorn_cage",
    "ember_wyrm": "flame_sweep",
    "void_knight": "void_charge",
}
EXPECTED_CLIPS = {"idle": 6, "attack": 8, "hit": 4, "death": 10}
MIN_UNIQUE = {"idle": 5, "attack": 7, "hit": 3, "death": 9}
EXPECTED_PIVOT = {"units": "normalized-bottom-left", "x": 0.5, "y": 0.12}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("baseline", type=Path)
    parser.add_argument("candidate", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    baseline = args.baseline.resolve()
    candidate = args.candidate.resolve()
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)

    audit = audit_batch(baseline, candidate)
    for key, label, *_ in BOSSES:
        old = CharacterFrames(baseline, key)
        new = CharacterFrames(candidate, key)
        create_motion_sheet(new, label, output / f"{key}_full_motion.png")
        create_readability_sheet(old, new, label, output / f"{key}_readability.png")
    create_lineup_sheet(baseline, candidate, audit, output / "bosses_lineup.png")

    sheet_paths = sorted(output.glob("*.png"))
    audit["reviewSheets"] = {
        path.name: {"sha256": sha256(path), "bytes": path.stat().st_size}
        for path in sheet_paths
    }
    audit["reviewSheetCount"] = len(sheet_paths)
    audit_path = output / "bosses_audit.json"
    audit_path.write_text(json.dumps(audit, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(
        f"Audited {audit['summary']['assetCount']} bosses and "
        f"{audit['summary']['frameCount']} frames; wrote {len(sheet_paths)} review sheets to {output}"
    )


def audit_batch(baseline: Path, candidate: Path) -> dict:
    baseline_manifest_path = baseline / "asset_manifest.json"
    candidate_manifest_path = candidate / "asset_manifest.json"
    baseline_manifest = read_json(baseline_manifest_path)
    candidate_manifest = read_json(candidate_manifest_path)
    expected_keys = [record[0] for record in BOSSES]
    candidate_keys = sorted(entry["key"] for entry in candidate_manifest["assets"])
    if candidate_keys != sorted(expected_keys):
        raise ValueError(f"Candidate must contain exactly {expected_keys}; found {candidate_keys}")
    if candidate_manifest.get("pipelineVersion", 0) < 3:
        raise ValueError("Candidate pipelineVersion must be at least 3")
    if candidate_manifest.get("generatedBatch") != "bosses" and not master_tier.composed_and_bound(candidate_manifest):
        # A composed master-tier candidate is generated by the render batch rather than by the bosses batch,
        # and it is accepted only when the master-tier review explains every asset in it.
        raise ValueError("Candidate must be generated by the exact bosses batch")
    # The page ceiling is a property of the atlas contract (4096 since Phase 54), not of a batch: what matters
    # is that it is a legal ceiling and that every page in the candidate lives inside it.
    page_limit = candidate_manifest.get("maxAtlasPageSize")
    if page_limit not in (2048, 4096):
        raise ValueError(f"Candidate max atlas page size {page_limit!r} is not a legal atlas ceiling")
    for entry in candidate_manifest["assets"]:
        if entry["sheetWidth"] > page_limit or entry["sheetHeight"] > page_limit:
            raise ValueError(f"{entry['key']} does not fit inside the candidate's own page ceiling")
    if candidate_manifest.get("frameRate") != 12:
        raise ValueError("Candidate frame rate must remain 12 fps")
    if candidate_manifest.get("renderSupersample") != 2:
        raise ValueError("Candidate must use 2x supersampling")
    if candidate_manifest.get("opaqueRenderSamples") != 28:
        raise ValueError("Candidate must use 24 opaque samples")
    if candidate_manifest.get("renderTierTop") != [3, 36]:
        raise ValueError("Candidate must carry the Phase 28.3 tier fingerprint")

    required_bones = candidate_manifest.get("requiredBones", [])
    if len(required_bones) != 25 or len(set(required_bones)) != 25:
        raise ValueError("Boss rigs must expose the locked 25-bone contract")

    composed_candidate = master_tier.composed_and_bound(candidate_manifest)
    baseline_entries = {entry["key"]: entry for entry in baseline_manifest["assets"]}
    candidate_entries = {entry["key"]: entry for entry in candidate_manifest["assets"]}
    records = []
    total_frames = 0
    global_margins = {side: 10_000 for side in ("left", "top", "right", "bottom")}
    total_decoded = 0

    for key, label, revision, rig_profile, animation_profile in BOSSES:
        if key not in baseline_entries:
            raise ValueError(f"Baseline manifest is missing {key}")
        entry = candidate_entries[key]
        validate_metadata(entry, key, revision, rig_profile, animation_profile, required_bones)
        if key in master_tier.master_tier_keys(candidate_manifest):
            master_tier.assert_bound(candidate, key, entry)
        frame_size, _, _ = master_tier.bound_geometry(key, (256, 2048, 1024))
        metadata_entry = read_json(candidate / "sprites" / f"{key}.json")
        if metadata_entry != entry:
            raise ValueError(f"{key} manifest and per-asset metadata differ")
        baseline_character = CharacterFrames(baseline, key)
        candidate_character = CharacterFrames(candidate, key)
        clip_records = {}
        asset_margins = {side: 10_000 for side in global_margins}
        all_hashes: list[str] = []

        for clip, expected_count in EXPECTED_CLIPS.items():
            regions = sorted(entry["clips"].get(clip, []), key=lambda value: value["index"])
            if len(regions) != expected_count:
                raise ValueError(f"{key} {clip} has {len(regions)} frames, expected {expected_count}")
            if [region["index"] for region in regions] != list(range(expected_count)):
                raise ValueError(f"{key} {clip} frame indices are not contiguous")
            frame_hashes = []
            clip_margins = {side: 10_000 for side in global_margins}
            for index, region in enumerate(regions):
                if region.get("page", 0) != 0:
                    raise ValueError(f"{key} must remain a single-page atlas")
                if region["width"] != frame_size or region["height"] != frame_size:
                    raise ValueError(
                        f"{key} {clip}/{index} is not a native {frame_size} px frame"
                    )
                frame = candidate_character.frame(clip, index)
                alpha_box = frame.getchannel("A").getbbox()
                if alpha_box is None:
                    raise ValueError(f"{key} {clip}/{index} is empty")
                left, top, right, bottom = alpha_box
                margins = {
                    "left": left,
                    "top": top,
                    "right": frame.width - right,
                    "bottom": frame.height - bottom,
                }
                if min(margins.values()) < 2:
                    raise ValueError(f"{key} {clip}/{index} approaches the frame boundary: {margins}")
                for side, margin in margins.items():
                    clip_margins[side] = min(clip_margins[side], margin)
                    asset_margins[side] = min(asset_margins[side], margin)
                    global_margins[side] = min(global_margins[side], margin)
                digest = hashlib.sha256(frame.tobytes()).hexdigest()
                frame_hashes.append(digest)
                all_hashes.append(digest)
            unique_count = len(set(frame_hashes))
            if unique_count < MIN_UNIQUE[clip]:
                raise ValueError(f"{key} {clip} has only {unique_count} unique visible frames")
            clip_records[clip] = {
                "frameCount": expected_count,
                "uniqueVisibleFrames": unique_count,
                "minimumAlphaMargins": clip_margins,
            }
            total_frames += expected_count

        baseline_sheet = baseline / baseline_entries[key]["sheet"]
        candidate_sheet = candidate / entry["sheet"]
        candidate_atlas = candidate / entry["atlas"]
        candidate_metadata = candidate / "sprites" / f"{key}.json"
        baseline_hash = sha256(baseline_sheet)
        candidate_hash = sha256(candidate_sheet)
        if baseline_hash == candidate_hash:
            if key in master_tier.master_tier_keys(candidate_manifest):
                # A composed key that ships the baseline's own bytes is not a composition, it is a silent
                # fall-back to the reviewed tier -- and the review document names every key it binds by hash.
                raise ValueError(f"{key} is composed but ships the baseline's own bytes")
            if not composed_candidate:
                raise ValueError(f"{key} candidate sheet is byte-identical to the baseline")
        if len(set(all_hashes)) < 20:
            raise ValueError(f"{key} has insufficient full-set motion diversity")
        for sheet in entry["sheets"]:
            total_decoded += int(sheet["width"]) * int(sheet["height"]) * 4

        records.append({
            "key": key,
            "label": label,
            "baselineSheetSha256": baseline_hash,
            "candidateSheetSha256": candidate_hash,
            "candidateAtlasSha256": sha256(candidate_atlas),
            "candidateMetadataSha256": sha256(candidate_metadata),
            "modelRevision": revision,
            "rigProfile": rig_profile,
            "animationProfile": animation_profile,
            "signatureAttack": SIGNATURE_ATTACKS[key],
            "triangles": entry["triangles"],
            "meshParts": entry["meshParts"],
            "materialCount": entry["materialCount"],
            "rigBoneCount": entry["rigBoneCount"],
            "minimumAlphaMargins": asset_margins,
            "clips": clip_records,
        })

    decoded_limit = 48 * 1024 * 1024
    if composed_candidate:
        # See the enemy generator: a composed candidate ships at the render's own resolution, so the ceiling it
        # has to live inside is the catalog's, and the master-tier review carries that arithmetic.
        ceiling = read_json(candidate_manifest_path)["decodedCatalogBudgetBytes"]
        if total_decoded > ceiling:
            raise ValueError(
                f"Composed boss batch decodes to {total_decoded} bytes, over the catalog ceiling {ceiling}"
            )
    elif total_decoded > decoded_limit:
        raise ValueError(f"Boss batch decodes to {total_decoded} bytes, over {decoded_limit}")
    return {
        "schemaVersion": 1,
        "batch": "bosses-premium-v2",
        "baselineManifestSha256": sha256(baseline_manifest_path),
        "candidateManifestSha256": sha256(candidate_manifest_path),
        "expectedKeys": expected_keys,
        "frameContract": EXPECTED_CLIPS,
        "minimumUniqueVisibleFrames": MIN_UNIQUE,
        "assets": records,
        "summary": {
            "assetCount": len(records),
            "frameCount": total_frames,
            "singlePageAtlasCount": len(records),
            "decodedBytes": total_decoded,
            "decodedBudgetBytes": decoded_limit,
            "decodedBytesNote": (
                "Measured on the candidate that shipped. Keys the master-tier review composes (roadmap R5.2) "
                "are at the render's own resolution there rather than at this batch's reviewed geometry, and the "
                "master-tier review carries the arithmetic against the catalog ceiling."
            ),
            "minimumAlphaMargins": global_margins,
            "minimumTriangles": min(record["triangles"] for record in records),
            "maximumTriangles": max(record["triangles"] for record in records),
            "minimumMeshParts": min(record["meshParts"] for record in records),
            "minimumMaterialCount": min(record["materialCount"] for record in records),
        },
    }


def validate_metadata(
    entry: dict,
    key: str,
    revision: str,
    rig_profile: str,
    animation_profile: str,
    required_bones: list[str],
) -> None:
    frame_size, sheet_width, sheet_height = master_tier.bound_geometry(key, (256, 2048, 1024))
    expected = {
        "family": "boss",
        "builder": key,
        "frameClass": "boss",
        "frameSize": frame_size,
        "sheetWidth": sheet_width,
        "sheetHeight": sheet_height,
        "pivot": EXPECTED_PIVOT,
        "alphaMode": "STRAIGHT_RGBA",
        "frameRate": 12,
        "renderSupersample": 3,
        "renderSamples": 36,
        "boneAnimated": True,
        "visualQuality": master_tier.bound_visual_quality(key, "studio-v3"),
        "modelRevision": revision,
        "rigProfile": rig_profile,
        "animationProfile": animation_profile,
        "unique_attack": SIGNATURE_ATTACKS[key],
    }
    for field, value in expected.items():
        if entry.get(field) != value:
            raise ValueError(f"{key} {field} is {entry.get(field)!r}; expected {value!r}")
    if entry.get("bones") != sorted(required_bones):
        raise ValueError(f"{key} does not match the locked rig bone names")
    if entry.get("rigBoneCount") != 25:
        raise ValueError(f"{key} must retain all 25 bones")
    if not 1_200 <= int(entry.get("triangles", 0)) <= 6_000:
        raise ValueError(f"{key} triangle count is outside the premium boss budget")
    if int(entry.get("meshParts", 0)) < 45:
        raise ValueError(f"{key} requires at least 45 purposeful mesh parts")
    if int(entry.get("materialCount", 0)) < 8:
        raise ValueError(f"{key} requires at least eight coherent materials")
    _, sheet_width, sheet_height = master_tier.bound_geometry(key, (256, 2048, 1024))
    expected_sheet = {
        "decodedBytes": sheet_width * sheet_height * 4,
        "file": f"sprites/{key}.png",
        "height": sheet_height,
        "width": sheet_width,
    }
    if entry.get("sheets") != [expected_sheet]:
        raise ValueError(
            f"{key} must remain on one exact {sheet_width}x{sheet_height} atlas page"
        )
    landmarks = entry.get("silhouetteLandmarks")
    if not isinstance(landmarks, list) or len(landmarks) < 4 or not all(landmarks):
        raise ValueError(f"{key} requires at least four silhouette landmarks")
    if not entry.get("surfaceLanguage"):
        raise ValueError(f"{key} is missing its surface language")


def create_lineup_sheet(baseline: Path, candidate: Path, audit: dict, output: Path) -> None:
    width, height = 1_900, 1_390
    canvas = canvas_base(width, height, "BOSSES — PREMIUM V2 LINEUP & SIGNATURE HIERARCHY")
    draw = ImageDraw.Draw(canvas)
    text(
        draw,
        (width // 2, 77),
        "One shared scale: baseline idle, premium idle, and premium attack impact for every Boss.",
        18,
        anchor="ma",
        color="#AFC5BE",
    )
    row_labels = ("BASELINE", "PREMIUM IDLE", "ATTACK IMPACT", "SILHOUETTE")
    row_positions = (150, 380, 610, 840)
    for label, y in zip(row_labels, row_positions):
        text(draw, (30, y + 100), label, 18, bold=True, anchor="lm", color="#F2D58A")
    audit_by_key = {entry["key"]: entry for entry in audit["assets"]}
    for column, (key, label, *_rest) in enumerate(BOSSES):
        old = CharacterFrames(baseline, key)
        new = CharacterFrames(candidate, key)
        x = 200 + column * 420
        signature = SIGNATURE_ATTACKS[key].replace("_", " ").upper()
        text(draw, (x + 180, 118), label.upper(), 22, bold=True, anchor="ma")
        text(draw, (x + 180, 142), signature, 14, bold=True, anchor="ma", color="#F2D58A")
        frames = (old.frame("idle", 0), new.frame("idle", 0), new.frame("attack", 4))
        modes = ("checker", "checker", "checker", "silhouette")
        for y, sprite, mode in zip(row_positions, frames + (frames[1],), modes):
            card = presentation_card(sprite, mode, 360, 205)
            canvas.paste(card.convert("RGB"), (x, y))
            draw.rounded_rectangle((x, y, x + 360, y + 205), 10, outline="#58706A", width=2)
        record = audit_by_key[key]
        text(
            draw,
            (x + 180, 1302),
            f"{record['triangles']:,} triangles  •  {record['meshParts']} purposeful parts",
            15,
            anchor="ma",
            color="#AFC5BE",
        )
        text(
            draw,
            (x + 180, 1327),
            f"{record['materialCount']} coherent materials  •  25-bone animated rig",
            15,
            anchor="ma",
            color="#AFC5BE",
        )
    grade = grade_row(CharacterFrames(candidate, BOSSES[0][0]).frame("idle", 0))
    canvas.paste(grade.convert("RGB"), ((width - grade.width) // 2, 1075))
    text(draw, ((width // 2), 1060), f"STAGE GRADE — {BOSSES[0][1].upper()} (REPRESENTATIVE)",
         16, bold=True, anchor="ma", color="#F2D58A")
    canvas.save(output, optimize=True)


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


if __name__ == "__main__":
    main()
