#!/usr/bin/env python3
"""Review the hero-worn boots + weapon overlay subset (Phase 28.4/29.4)."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import create_equipment_batch_review as eq

# Studio-v3 contact-sheet mode: baseline premium-v2 vs candidate studio-v3
STUDIO_TIER_BASELINE_QUALITY = "premium-v2"
STUDIO_TIER_CANDIDATE_QUALITY = "studio-v3"

OVERLAY_VISUAL_SLOTS = ("boots", "weapon")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("baseline", type=Path)
    parser.add_argument("candidate", type=Path)
    parser.add_argument("hero_root", type=Path)
    parser.add_argument("catalog", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    baseline = args.baseline.resolve()
    candidate = args.candidate.resolve()
    hero_root = args.hero_root.resolve()
    catalog_path = args.catalog.resolve()
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)

    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
    items = [item for item in catalog["items"]
             if item["visualSlot"] in OVERLAY_VISUAL_SLOTS]
    if not items:
        raise ValueError("Overlay review requires at least one boots/weapon item")

    manifest_path = candidate / "asset_manifest.json"
    candidate_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if candidate_manifest.get("generatedBatch") != "equipment-overlay":
        raise ValueError("Candidate must be generated by the equipment-overlay batch")
    candidate_assets = candidate_manifest["assets"]
    candidate_by_key = {asset["key"]: asset for asset in candidate_assets}
    if len(candidate_by_key) != len(candidate_assets):
        raise ValueError("Duplicate overlay candidate key")
    expected_keys = {f"equipment_{item['id']}" for item in items}
    if set(candidate_by_key) != expected_keys:
        raise ValueError(
            f"Overlay candidate key mismatch: {sorted(set(candidate_by_key) ^ expected_keys)}"
        )

    hero = eq.Frames(hero_root, "sprites", "hero")
    audit = eq.audit_batch(candidate, hero, items, candidate_by_key,
                           catalog_path, manifest_path)
    audit["scope"] = "hero-worn-boots-and-weapon-only"
    eq.create_icon_sheets(baseline, candidate, items, output)
    eq.create_composite_sheets(candidate, hero, items, output)
    total_pages = (len(items) + 7) // 8
    review_sheet_names = [
        *(f"equipment_icons_{tier.lower()}.png" for tier in eq.TIERS
          if any(item["tier"] == tier for item in items)),
        *(f"equipment_composites_{page}.png" for page in range(1, total_pages + 1)),
    ]
    audit["reviewSheets"] = {name: eq.sha256_file(output / name)
                             for name in review_sheet_names}
    (output / "equipment_overlay_audit.json").write_text(
        json.dumps(audit, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Audited all {len(items) * 28} overlay frames in {output}")


if __name__ == "__main__":
    main()
