#!/usr/bin/env python3
"""The master tier, bound by its own review rather than assumed.

Roadmap R5.2 composes the runtime tier out of the genuine master renders *at the resolution they were
rendered at*, which is deliberately not the reviewed per-batch geometry (192 px frames on a 1920x768 page).
A batch's review generator therefore has to be able to tell a composed sheet from a candidate that simply
claims a bigger page, and it asks two questions here instead of trusting a number:

* **is this key composed?** -- the manifest's `masterTier` block names the keys, and nothing else does;
* **is the composed sheet the one the review bound?** -- `docs/art_reviews/master_tier_review.json`, written by
  `create_master_tier_review.py`, carries each composed key's geometry and the sha256 of both the sheet and its
  atlas, and it is written only when the provenance measurement classifies every one of those sheets as an
  independent render.

A generator that cannot answer yes to both keeps refusing the candidate, so a 384 px sheet is still
evidence-bound: to the render batch it came from, to the review document that accepted it, and to a hash.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[2]
MANIFEST_RELATIVE = "android/assets/generated/asset_manifest.json"
REVIEW_RELATIVE = "docs/art_reviews/master_tier_review.json"


def master_tier_keys(manifest: dict) -> set[str]:
    block = manifest.get("masterTier")
    if not block:
        return set()
    return {str(key) for key in block.get("sheets", [])}


def load_review() -> dict:
    path = REPOSITORY / REVIEW_RELATIVE
    if not path.is_file():
        raise SystemExit(f"the master tier has no review binding: {REVIEW_RELATIVE} is missing")
    return json.loads(path.read_text(encoding="utf-8"))


def bound_geometry(key: str, default: tuple[int, int, int]) -> tuple[int, int, int]:
    """(frameSize, sheetWidth, sheetHeight) for a key: the reviewed numbers, or the composed ones if bound."""
    review = load_review()
    record = review.get("sheets", {}).get(key)
    if record is None:
        return default
    return int(record["frameSize"]), int(record["sheetWidth"]), int(record["sheetHeight"])


def bound_visual_quality(key: str, default: str) -> str:
    """The render line a composed sheet carries, which is the render batch's rather than the reviewed tier's."""
    record = load_review().get("sheets", {}).get(key)
    return str(record["visualQuality"]) if record else default


def assert_bound(root: Path, key: str, entry: dict) -> None:
    """Refuse a composed sheet whose pixels are not the ones the master-tier review bound by hash."""
    review = load_review()
    record = review.get("sheets", {}).get(key)
    if record is None:
        raise SystemExit(f"{key} is composed but the master-tier review does not cover it")
    sheet = root / entry["sheet"]
    if hashlib.sha256(sheet.read_bytes()).hexdigest() != record["sheetSha256"]:
        raise SystemExit(f"{key}: the shipped sheet is not the one the master-tier review bound")
    atlas = root / entry["atlas"]
    if hashlib.sha256(atlas.read_bytes()).hexdigest() != record["atlasSha256"]:
        raise SystemExit(f"{key}: the shipped atlas is not the one the master-tier review bound")


def composed_and_bound(manifest: dict) -> bool:
    """Whether every key this manifest composes is one the master-tier review bound, which is how a composed
    candidate is told from a candidate that was simply generated by the wrong batch. A batch that composes
    nothing cannot claim this and is held to its own render batch."""
    composed = master_tier_keys(manifest)
    return bool(composed) and composed <= set(load_review().get("sheets", {}))
