#!/usr/bin/env python3
"""Keep every art review document honest about the texture revision labels it covers.

The 2026-09-16 audit found assets whose `modelRevision` was a label their review document never
mentioned, so a manifest could carry a new revision string and no review would object. This tool reads
the committed manifest and writes a generated block into each referenced review document listing exactly
the labels (and how many assets use each) that the manifest ships. `ReviewLabelBindingTest` in core then
requires every asset's label to appear in its own review document, so the binding is enforced rather
than trusted.

Usage:
    python3 tools/visual/write_review_labels.py            # rewrite blocks
    python3 tools/visual/write_review_labels.py --check    # fail if a block is stale/missing
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[2]
MANIFEST = REPOSITORY / "android/assets/generated/asset_manifest.json"
BEGIN = "<!-- BEGIN GENERATED: texture revision labels -->"
END = "<!-- END GENERATED: texture revision labels -->"


def collect() -> dict[str, dict[str, int]]:
    manifest = json.loads(MANIFEST.read_text())
    by_document: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for asset in manifest["assets"]:
        review = asset.get("categoryReview") or {}
        document = review.get("document")
        revision = asset.get("modelRevision")
        if not document or not revision:
            raise SystemExit(f"{asset['key']}: missing categoryReview.document or modelRevision")
        by_document[document][revision] += 1
    return {document: dict(labels) for document, labels in by_document.items()}


def build_block(labels: dict[str, int]) -> str:
    rows = "\n".join(
        f"| `{label}` | {count} |" for label, count in sorted(labels.items(), key=lambda item: (-item[1], item[0]))
    )
    return (
        f"{BEGIN}\n"
        "## Texture revision labels\n\n"
        "Generated by `tools/visual/write_review_labels.py` from "
        "`android/assets/generated/asset_manifest.json`; do not edit by hand. "
        "Every asset must carry one of the labels listed here, and `ReviewLabelBindingTest` fails the "
        "build if a manifest revision is missing from the document that is supposed to review it.\n\n"
        "| Revision label | Assets |\n| --- | --- |\n"
        f"{rows}\n"
        f"{END}"
    )


def apply(path: Path, block: str) -> bool:
    text = path.read_text()
    if BEGIN in text and END in text:
        start = text.index(BEGIN)
        end = text.index(END) + len(END)
        updated = text[:start] + block + text[end:]
    else:
        marker = "## Final decision"
        if marker in text:
            index = text.index(marker)
            updated = text[:index] + block + "\n\n" + text[index:]
        else:
            updated = text.rstrip("\n") + "\n\n" + block + "\n"
    if updated == text:
        return False
    path.write_text(updated)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="do not write, report stale documents")
    args = parser.parse_args()

    documents = collect()
    changed: list[str] = []
    for document, labels in sorted(documents.items()):
        path = REPOSITORY / document
        if not path.is_file():
            print(f"missing review document {document}", file=sys.stderr)
            return 1
        block = build_block(labels)
        if args.check:
            text = path.read_text()
            if block not in text:
                print(f"stale generated block in {document}", file=sys.stderr)
                return 1
            continue
        if apply(path, block):
            changed.append(document)

    if args.check:
        print(f"review label blocks current in {len(documents)} documents")
        return 0
    for document in changed:
        print(f"updated {document}")
    print(f"{len(documents)} review documents carry generated label blocks, {len(changed)} written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
