#!/usr/bin/env python3
"""Measure every committed audio file and gate its level (roadmap R6.2).

R6.2 asks for "a measured peak level each", and measured is the operative word: the cue table says what a cue
should sound like, and this says what the bytes actually do. Every `.ogg` under `android/assets/audio` is
decoded, and its peak, RMS, length and channel count are written to `docs/audio/LEVELS.md`.

Two things fail the gate:

* a file whose peak is above the ceiling (0.94, about -0.5 dBFS). Vorbis can overshoot the peak it was given,
  and a cue that clips on a phone is a defect nobody forgives;
* a file that is committed but missing from the document, or a document row for a file that is not committed.
  The document is generated, so drift means somebody edited it by hand or added an asset without measuring it.

Exit codes match the rest of the repository's tools: 0 pass, 1 fail, 2 nothing to measure.

Usage:
    python3 tools/audio/check_audio_levels.py [--write] [--check]
"""
from __future__ import annotations

import argparse
import pathlib
import sys

import numpy as np

try:
    import soundfile as sf
except ImportError:  # pragma: no cover - CI installs it in the step that runs this
    print("soundfile is required: python3 -m pip install soundfile")
    raise SystemExit(2)

ROOT = pathlib.Path(__file__).resolve().parents[2]
ASSET_ROOT = ROOT / "android" / "assets"
AUDIO_ROOT = ASSET_ROOT / "audio"
DOC = ROOT / "docs" / "audio" / "LEVELS.md"

#: Peak ceiling in linear amplitude, comfortably under full scale: about -0.5 dBFS.
PEAK_CEILING = 0.94
#: A file quieter than this is inaudible on a phone speaker and is almost certainly a mistake.
PEAK_FLOOR = 0.08


def measure(path: pathlib.Path) -> dict:
    samples, rate = sf.read(path, dtype="float32")
    if samples.ndim == 1:
        flat = samples
    else:
        flat = samples.mean(axis=1)
    peak = float(np.max(np.abs(samples))) if len(samples) else 0.0
    rms = float(np.sqrt(np.mean(flat ** 2))) if len(flat) else 0.0
    return {
        "path": path.relative_to(ASSET_ROOT).as_posix(),
        "seconds": len(flat) / rate,
        "rate": rate,
        "channels": 1 if samples.ndim == 1 else samples.shape[1],
        "peak": peak,
        "rms": rms,
    }


def committed_files() -> list[pathlib.Path]:
    if not AUDIO_ROOT.is_dir():
        return []
    return sorted(path for path in AUDIO_ROOT.rglob("*.ogg") if path.is_file())


def render(rows: list[dict]) -> str:
    lines = [
        "# Measured Audio Levels",
        "",
        "Generated by `tools/audio/check_audio_levels.py` (roadmap R6.2) -- do not edit by hand. Each row is a",
        "decoded measurement of the committed file, not the level the cue table asks for; the two are compared by",
        "`AudioContractTest` and every cue's own peak is asserted to sit under the ceiling.",
        "",
        f"Ceiling: peak <= {PEAK_CEILING:.2f}. Floor: peak >= {PEAK_FLOOR:.2f}, because a cue nobody can hear is",
        "not a cue.",
        "",
        "| File | Length (s) | Rate | Channels | Peak | Peak (dBFS) | RMS |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        peak_db = 20 * np.log10(max(row["peak"], 1e-6))
        lines.append(
            f"| `{row['path']}` | {row['seconds']:.2f} | {row['rate']} | {row['channels']} "
            f"| {row['peak']:.3f} | {peak_db:.1f} | {row['rms']:.3f} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="rewrite docs/audio/LEVELS.md")
    parser.add_argument("--check", action="store_true", help="fail if the document is out of date")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    files = committed_files()
    if not files:
        print("AUDIO NOT MEASURED: no committed .ogg files under android/assets/audio")
        return 2

    rows = [measure(path) for path in files]
    document = render(rows)

    failures = []
    for row in rows:
        if row["peak"] > PEAK_CEILING:
            failures.append(f"{row['path']}: peak {row['peak']:.3f} is above the ceiling {PEAK_CEILING:.2f}")
        if row["peak"] < PEAK_FLOOR:
            failures.append(f"{row['path']}: peak {row['peak']:.3f} is below the floor {PEAK_FLOOR:.2f}")

    if args.write:
        DOC.parent.mkdir(parents=True, exist_ok=True)
        DOC.write_text(document, encoding="utf-8")
        if not args.quiet:
            print(f"wrote {DOC.relative_to(ROOT)}: {len(rows)} files measured")

    if args.check:
        current = DOC.read_text(encoding="utf-8") if DOC.exists() else ""
        if current != document:
            failures.append(f"{DOC.relative_to(ROOT)} is out of date; run with --write")

    if failures:
        for failure in failures:
            print(f"FAIL {failure}")
        return 1

    if not args.quiet:
        loudest = max(rows, key=lambda row: row["peak"])
        print(
            f"{len(rows)} audio files measured; loudest {loudest['path']} at {loudest['peak']:.3f} "
            f"({20 * np.log10(max(loudest['peak'], 1e-6)):.1f} dBFS)"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
