"""Tests for the first-party ETC2 encoder and the KTX container it writes (roadmap R8.1).

The gates that matter are the first two, and they are *not* round trips:

* four blocks produced by Google's `etc1` reference implementation -- the encoder/decoder pair libGDX ships as
  JNI and Android's own tooling embeds -- are decoded here and compared pixel for pixel;
* streams this encoder wrote on 2026-09-17 are decoded again and compared with what Google's `swiftshader`
  decoder made of them (see `driver_vectors.py`), because a round trip agrees with itself even when both of its
  halves read the layout the same wrong way. That is what happened to the punchthrough format: every test in
  this file passed while an emulator disagreed with this module by 247 levels on an alpha-perfect picture.

The rest are round trips and negative controls: an encoder that produced valid-looking bytes which do not decode
back is not an encoder, and a gate that cannot fail is not a gate.
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path

import numpy as np
from PIL import Image

TOOLS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(TOOLS))
sys.path.insert(0, str(TOOLS / "texture"))

sys.path.insert(0, str(Path(__file__).resolve().parent))

import driver_vectors  # noqa: E402
import etc2  # noqa: E402
import ktx  # noqa: E402

#: Block bytes and the pixels the reference decoder produced from them. Generated by running Google's `etc1`
#: implementation (the source libGDX compiles into its JNI library) over four 4x4 patches: a gradient, a flat
#: colour, a hard edge and a noisy patch. The flat one is a *differential* block, which this encoder never emits
#: and therefore has to be able to read.
REFERENCE_BLOCKS = (
    (
        "gradient",
        "3368c60237379393",
        "2963be2963be4263ad4263ad2963be2f69c44263ad4869b32f69c4336dc84869b34c6db7336dc83973ce4c6db75273bd",
    ),
    (
        "flat",
        "88888802ffff0000",
        "8a" * 48,
    ),
    (
        "edge",
        "1e2c4b0000000000",
        "132446132446f0cebdf0cebd132446132446f0cebdf0cebd132446132446f0cebdf0cebd132446132446f0cebdf0cebd",
    ),
    (
        "noisy",
        "6535984d159fa25b",
        "49167c49167c5d2a905d2a9049167c6f3ca28350b68350b648487b7f7fb248487b6262952b2b5e48487b6262957f7fb2",
    ),
)


def synthetic_sheet(size: int = 64) -> np.ndarray:
    """A sheet with the three things a sprite has: flat ground, soft shading, and a hard mask edge."""
    ys, xs = np.mgrid[0:size, 0:size]
    sheet = np.zeros((size, size, 4), dtype=np.uint8)
    sheet[..., 0] = np.clip(30 + 2 * xs, 0, 255)
    sheet[..., 1] = np.clip(120 + ys, 0, 255)
    sheet[..., 2] = np.clip(200 - xs // 2, 0, 255)
    sheet[..., 3] = np.where((xs - size // 2) ** 2 + (ys - size // 2) ** 2 < (size // 3) ** 2, 255, 0)
    return sheet


class ReferenceLayoutTest(unittest.TestCase):
    def test_the_decoder_matches_the_reference_implementation(self) -> None:
        for name, block, pixels in REFERENCE_BLOCKS:
            with self.subTest(block=name):
                expected = np.frombuffer(bytes.fromhex(pixels), dtype=np.uint8).reshape(4, 4, 3)
                decoded = etc2.decode_blocks(bytes.fromhex(block), 4, 4, punchthrough=False)
                np.testing.assert_array_equal(decoded[..., :3], expected)
                self.assertTrue((decoded[..., 3] == 255).all())

    def test_a_block_that_is_not_eight_bytes_is_refused(self) -> None:
        with self.assertRaises(ValueError):
            etc2.decode_blocks(bytes(7), 4, 4, punchthrough=False)

    def test_punchthrough_marks_only_the_pixels_it_was_given(self) -> None:
        """A block whose low word is all index-2 bits decodes to a fully clear 4x4 tile."""
        block = bytes.fromhex("00000000" + "ffff0000")
        decoded = etc2.decode_blocks(block, 4, 4, punchthrough=True)
        self.assertTrue((decoded[..., 3] == 0).all())


class DriverLayoutTest(unittest.TestCase):
    """The punchthrough layout, held to a decoder this repository did not write.

    `driver_vectors.py` records both halves of the evidence: the block streams, and the pixels Google's
    `swiftshader` decoder produced from them. The first case here decodes those streams again -- so a change to
    the decoder that quietly reinterprets the layout fails here instead of on a device. The second case pins the
    encoder's side of the same contract with the structural rules that were broken, because a stream can only be
    checked against a driver's *rules* without a driver.
    """

    def test_the_decoder_matches_a_driver_pixel_for_pixel(self) -> None:
        for vector in driver_vectors.VECTORS:
            with self.subTest(stream=vector.name):
                decoded = etc2.decode_blocks(
                    bytes.fromhex(vector.blocks_hex), vector.width, vector.height, punchthrough=True
                )
                expected = np.frombuffer(bytes.fromhex(vector.pixels_hex), dtype=np.uint8).reshape(
                    vector.height, vector.width, 4
                )
                np.testing.assert_array_equal(decoded, expected)

    def test_a_clear_pixel_decodes_to_black_not_to_its_base_colour(self) -> None:
        """The last behaviour the device comparison tripped over, on its own so a regression names itself."""
        covered = 0
        for vector in driver_vectors.VECTORS:
            pixels = np.frombuffer(bytes.fromhex(vector.pixels_hex), dtype=np.uint8).reshape(
                vector.height, vector.width, 4
            )
            clear = pixels[..., 3] == 0
            if not clear.any():
                continue
            covered += int(clear.sum())
            self.assertTrue(
                (pixels[clear][:, :3] == 0).all(),
                f"{vector.name}: the driver gave a clear pixel a colour",
            )
        self.assertGreater(covered, 0, "no recorded stream had a clear pixel to check")

    def test_the_encoder_writes_the_layout_a_driver_reads(self) -> None:
        """The structural rules of the driver's decode path, on the blocks the encoder just wrote.

        These are the rules that were broken before the emulator was believed:

        * the colour part is the differential layout, so the five-bit bases and three-bit steps a decoder reads
          must add up inside the five-bit range -- a sum that leaves it is not a differential block at all but a
          T, H or planar one, and the colours come back from somewhere else entirely;
        * the flag bit is the opaque bit: a block that carries a clear pixel must declare itself non-opaque, and
          a block that declares itself opaque has no clear pixel in it;
        * the stream has to contain a clear pixel at all, or the rule above would be checked on nothing. The
          other direction -- a block that declares itself opaque, and the fixture's 58 of them -- is asserted in
          `test_device_fixture.py`, against the stream the device actually uploads.
        """
        payload = etc2.encode_blocks(synthetic_sheet(32), etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1)
        clear_blocks = 0
        for offset in range(0, len(payload), 8):
            high = int.from_bytes(payload[offset:offset + 4], "big")
            low = int.from_bytes(payload[offset + 4:offset + 8], "big")
            flag = (high >> 1) & 1
            bases = np.array([(high >> 27) & 0x1F, (high >> 19) & 0x1F, (high >> 11) & 0x1F])
            steps = np.array([(high >> 24) & 7, (high >> 16) & 7, (high >> 8) & 7])
            steps = np.where(steps > 3, steps - 8, steps)
            sums = bases + steps
            self.assertTrue(
                ((sums >= 0) & (sums <= 31)).all(),
                f"block {offset // 8} is read as T, H or planar, not differential: bases {bases} steps {steps}",
            )
            bits = np.arange(16)
            indices = ((low >> bits) & 1) | (((low >> (bits + 16)) & 1) << 1)
            clears = int((indices == etc2.PUNCHTHROUGH_INDEX).sum())
            clear_blocks += 1 if clears else 0
            if clears:
                self.assertEqual(
                    0, flag,
                    f"block {offset // 8} declares itself opaque and still carries a clear pixel",
                )
        self.assertGreater(clear_blocks, 0, "the stream carried no clear pixel to check the opaque bit on")


class EncoderRoundTripTest(unittest.TestCase):
    def test_a_flat_block_round_trips_exactly(self) -> None:
        flat = np.zeros((4, 4, 4), dtype=np.uint8)
        flat[..., :3] = 138
        flat[..., 3] = 255
        payload = etc2.encode_blocks(flat, etc2.ETC2_RGB8)
        decoded = etc2.decode_blocks(payload, 4, 4, punchthrough=False)
        self.assertTrue((decoded[..., :3] == 138).all(), "a flat colour must survive at least one exact level")

    def test_the_encoder_keeps_the_picture_recognisable(self) -> None:
        """A sprite encoded and decoded back is still the same picture.

        The bar here is deliberately modest: this test says the round trip *works*. What decides whether a sheet
        may ship compressed is the tool's own PSNR gate against the reference encoder, and that gate is where the
        number lives -- this encoder does not clear it yet, which the tool reports rather than hides.
        """
        sheet = synthetic_sheet()
        payload = etc2.encode_blocks(sheet, etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1)
        decoded = etc2.decode_blocks(payload, 64, 64, punchthrough=True)
        opaque = sheet[..., 3] == 255
        difference = (decoded[..., :3].astype(np.int32) - sheet[..., :3].astype(np.int32))[opaque]
        psnr = 10 * np.log10(255.0 ** 2 / float((difference.astype(np.float64) ** 2).mean()))
        self.assertGreater(psnr, 20.0, f"round-trip PSNR was {psnr:.2f} dB")

    def test_the_mask_survives_the_punchthrough_format(self) -> None:
        sheet = synthetic_sheet()
        payload = etc2.encode_blocks(sheet, etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1)
        decoded = etc2.decode_blocks(payload, 64, 64, punchthrough=True)
        self.assertTrue(
            ((decoded[..., 3] == 255) == (sheet[..., 3] == 255)).all(),
            "an opaque pixel must never come back clear in the punchthrough format",
        )

    def test_the_container_is_a_quarter_of_the_decoded_size(self) -> None:
        sheet = synthetic_sheet(64)
        payload = etc2.encode_blocks(sheet, etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1)
        self.assertEqual(len(payload), 64 * 64 // 2)
        self.assertEqual(etc2.decoded_bytes_per_pixel(etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1), 0.5)

    def test_the_alpha_measure_says_which_sheets_are_masks(self) -> None:
        mask = synthetic_sheet()
        soft = synthetic_sheet()
        soft[..., 3] = 128
        self.assertEqual(etc2.binary_alpha_fraction(mask), 1.0)
        self.assertEqual(etc2.binary_alpha_fraction(soft), 0.0)

    def test_an_unknown_format_is_refused(self) -> None:
        with self.assertRaises(ValueError):
            etc2.encode_blocks(synthetic_sheet(4), 0xABCD)


class KtxContainerTest(unittest.TestCase):
    def test_a_container_round_trips(self) -> None:
        payload = etc2.encode_blocks(synthetic_sheet(32), etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1)
        image = ktx.Image(
            width=32,
            height=32,
            gl_internal_format=etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1,
            gl_base_internal_format=ktx.GL_RGBA,
            payload=payload,
        )
        parsed = ktx.read(ktx.write(image))
        self.assertEqual(parsed, image)

    def test_junk_is_refused_rather_than_loaded(self) -> None:
        with self.assertRaises(ValueError):
            ktx.read(b"\x00" * 128)

    def test_a_truncated_payload_is_refused(self) -> None:
        payload = etc2.encode_blocks(synthetic_sheet(32), etc2.ETC2_RGB8)
        blob = ktx.write(
            ktx.Image(32, 32, etc2.ETC2_RGB8, ktx.GL_RGB, payload)
        )
        with self.assertRaises(ValueError):
            ktx.read(blob[:-16])


if __name__ == "__main__":
    unittest.main()


class EncodingGateTest(unittest.TestCase):
    """The decision the tool makes, tested on the two cases that must not become a payload."""

    def setUp(self) -> None:
        import encode_textures

        self.encode_textures = encode_textures

    def _sheet(self, image: np.ndarray, name: str) -> tuple:
        import tempfile

        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        root = Path(directory.name)
        Image.fromarray(image).save(root / name)
        return root, {"file": name, "width": image.shape[1], "height": image.shape[0],
                      "decodedBytes": int(image.shape[0] * image.shape[1] * 4)}

    def test_a_sheet_with_soft_alpha_is_declined_with_its_reason(self) -> None:
        sheet_image = synthetic_sheet(64)
        soft = sheet_image.copy()
        soft[..., 3] = np.where(soft[..., 3] > 0, 200, 0)
        root, sheet = self._sheet(soft, "soft.png")
        record = self.encode_textures.encode_sheet("soft_key", sheet, 32.0, root)
        self.assertFalse(record["encoded"])
        self.assertIn("soft alpha", record["reason"])

    def test_a_sheet_that_misses_the_quality_bar_is_declined_with_the_number(self) -> None:
        root, sheet = self._sheet(synthetic_sheet(64), "hard.png")
        record = self.encode_textures.encode_sheet("hard_key", sheet, 80.0, root)
        self.assertFalse(record["encoded"])
        self.assertIn("below the 80.00 dB bar", record["reason"])
        self.assertIsNotNone(record["psnrDb"])

    def test_a_sheet_that_clears_the_bar_is_encoded_and_measured(self) -> None:
        root, sheet = self._sheet(synthetic_sheet(64), "hard.png")
        record = self.encode_textures.encode_sheet("hard_key", sheet, 20.0, root)
        self.assertTrue(record["encoded"])
        self.assertEqual(record["encodedBytes"], 64 * 64 // 2)
        self.assertEqual(record["alphaAgreement"], 1.0)
        self.assertGreater(record["psnrDb"], 20.0)
