"""Tests for the first-party ETC2 encoder and the KTX container it writes (roadmap R8.1).

The gate that matters is the first one: four blocks produced by Google's `etc1` reference implementation -- the
encoder/decoder pair libGDX ships as JNI and Android's own tooling embeds -- are decoded here and compared pixel
for pixel. A layout error in this module would otherwise only show up as an ugly sprite on a device.

The rest are round trips and negative controls: an encoder that produced valid-looking bytes which do not decode
back is not an encoder, and a gate that cannot fail is not a gate.
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path

import numpy as np
from PIL import Image

TOOLS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(TOOLS))
sys.path.insert(0, str(TOOLS / "texture"))

import etc2  # noqa: E402
import ktx  # noqa: E402

#: Block bytes and the pixels the reference decoder produced from them. Generated by running Google's `etc1`
#: implementation (the source libGDX compiles into its JNI library) over four 4x4 patches: a gradient, a flat
#: colour, a hard edge and a noisy patch. The flat one is a *differential* block, which this encoder never emits
#: and therefore has to be able to read.
REFERENCE_BLOCKS = (
    (
        "gradient",
        "3368c60237379393",
        "2963be2963be4263ad4263ad2963be2f69c44263ad4869b32f69c4336dc84869b34c6db7336dc83973ce4c6db75273bd",
    ),
    (
        "flat",
        "88888802ffff0000",
        "8a" * 48,
    ),
    (
        "edge",
        "1e2c4b0000000000",
        "132446132446f0cebdf0cebd132446132446f0cebdf0cebd132446132446f0cebdf0cebd132446132446f0cebdf0cebd",
    ),
    (
        "noisy",
        "6535984d159fa25b",
        "49167c49167c5d2a905d2a9049167c6f3ca28350b68350b648487b7f7fb248487b6262952b2b5e48487b6262957f7fb2",
    ),
)


def synthetic_sheet(size: int = 64) -> np.ndarray:
    """A sheet with the three things a sprite has: flat ground, soft shading, and a hard mask edge."""
    ys, xs = np.mgrid[0:size, 0:size]
    sheet = np.zeros((size, size, 4), dtype=np.uint8)
    sheet[..., 0] = np.clip(30 + 2 * xs, 0, 255)
    sheet[..., 1] = np.clip(120 + ys, 0, 255)
    sheet[..., 2] = np.clip(200 - xs // 2, 0, 255)
    sheet[..., 3] = np.where((xs - size // 2) ** 2 + (ys - size // 2) ** 2 < (size // 3) ** 2, 255, 0)
    return sheet


class ReferenceLayoutTest(unittest.TestCase):
    def test_the_decoder_matches_the_reference_implementation(self) -> None:
        for name, block, pixels in REFERENCE_BLOCKS:
            with self.subTest(block=name):
                expected = np.frombuffer(bytes.fromhex(pixels), dtype=np.uint8).reshape(4, 4, 3)
                decoded = etc2.decode_blocks(bytes.fromhex(block), 4, 4, punchthrough=False)
                np.testing.assert_array_equal(decoded[..., :3], expected)
                self.assertTrue((decoded[..., 3] == 255).all())

    def test_a_block_that_is_not_eight_bytes_is_refused(self) -> None:
        with self.assertRaises(ValueError):
            etc2.decode_blocks(bytes(7), 4, 4, punchthrough=False)

    def test_punchthrough_marks_only_the_pixels_it_was_given(self) -> None:
        """A block whose low word is all index-2 bits decodes to a fully clear 4x4 tile."""
        block = bytes.fromhex("00000000" + "ffff0000")
        decoded = etc2.decode_blocks(block, 4, 4, punchthrough=True)
        self.assertTrue((decoded[..., 3] == 0).all())


class EncoderRoundTripTest(unittest.TestCase):
    def test_a_flat_block_round_trips_exactly(self) -> None:
        flat = np.zeros((4, 4, 4), dtype=np.uint8)
        flat[..., :3] = 138
        flat[..., 3] = 255
        payload = etc2.encode_blocks(flat, etc2.ETC2_RGB8)
        decoded = etc2.decode_blocks(payload, 4, 4, punchthrough=False)
        self.assertTrue((decoded[..., :3] == 138).all(), "a flat colour must survive at least one exact level")

    def test_the_encoder_keeps_the_picture_recognisable(self) -> None:
        """A sprite encoded and decoded back is still the same picture.

        The bar here is deliberately modest: this test says the round trip *works*. What decides whether a sheet
        may ship compressed is the tool's own PSNR gate against the reference encoder, and that gate is where the
        number lives -- this encoder does not clear it yet, which the tool reports rather than hides.
        """
        sheet = synthetic_sheet()
        payload = etc2.encode_blocks(sheet, etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1)
        decoded = etc2.decode_blocks(payload, 64, 64, punchthrough=True)
        opaque = sheet[..., 3] == 255
        difference = (decoded[..., :3].astype(np.int32) - sheet[..., :3].astype(np.int32))[opaque]
        psnr = 10 * np.log10(255.0 ** 2 / float((difference.astype(np.float64) ** 2).mean()))
        self.assertGreater(psnr, 20.0, f"round-trip PSNR was {psnr:.2f} dB")

    def test_the_mask_survives_the_punchthrough_format(self) -> None:
        sheet = synthetic_sheet()
        payload = etc2.encode_blocks(sheet, etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1)
        decoded = etc2.decode_blocks(payload, 64, 64, punchthrough=True)
        self.assertTrue(
            ((decoded[..., 3] == 255) == (sheet[..., 3] == 255)).all(),
            "an opaque pixel must never come back clear in the punchthrough format",
        )

    def test_the_container_is_a_quarter_of_the_decoded_size(self) -> None:
        sheet = synthetic_sheet(64)
        payload = etc2.encode_blocks(sheet, etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1)
        self.assertEqual(len(payload), 64 * 64 // 2)
        self.assertEqual(etc2.decoded_bytes_per_pixel(etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1), 0.5)

    def test_the_alpha_measure_says_which_sheets_are_masks(self) -> None:
        mask = synthetic_sheet()
        soft = synthetic_sheet()
        soft[..., 3] = 128
        self.assertEqual(etc2.binary_alpha_fraction(mask), 1.0)
        self.assertEqual(etc2.binary_alpha_fraction(soft), 0.0)

    def test_an_unknown_format_is_refused(self) -> None:
        with self.assertRaises(ValueError):
            etc2.encode_blocks(synthetic_sheet(4), 0xABCD)


class KtxContainerTest(unittest.TestCase):
    def test_a_container_round_trips(self) -> None:
        payload = etc2.encode_blocks(synthetic_sheet(32), etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1)
        image = ktx.Image(
            width=32,
            height=32,
            gl_internal_format=etc2.ETC2_RGB8_PUNCHTHROUGH_ALPHA1,
            gl_base_internal_format=ktx.GL_RGBA,
            payload=payload,
        )
        parsed = ktx.read(ktx.write(image))
        self.assertEqual(parsed, image)

    def test_junk_is_refused_rather_than_loaded(self) -> None:
        with self.assertRaises(ValueError):
            ktx.read(b"\x00" * 128)

    def test_a_truncated_payload_is_refused(self) -> None:
        payload = etc2.encode_blocks(synthetic_sheet(32), etc2.ETC2_RGB8)
        blob = ktx.write(
            ktx.Image(32, 32, etc2.ETC2_RGB8, ktx.GL_RGB, payload)
        )
        with self.assertRaises(ValueError):
            ktx.read(blob[:-16])


if __name__ == "__main__":
    unittest.main()


class EncodingGateTest(unittest.TestCase):
    """The decision the tool makes, tested on the two cases that must not become a payload."""

    def setUp(self) -> None:
        import encode_textures

        self.encode_textures = encode_textures

    def _sheet(self, image: np.ndarray, name: str) -> tuple:
        import tempfile

        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        root = Path(directory.name)
        Image.fromarray(image).save(root / name)
        return root, {"file": name, "width": image.shape[1], "height": image.shape[0],
                      "decodedBytes": int(image.shape[0] * image.shape[1] * 4)}

    def test_a_sheet_with_soft_alpha_is_declined_with_its_reason(self) -> None:
        sheet_image = synthetic_sheet(64)
        soft = sheet_image.copy()
        soft[..., 3] = np.where(soft[..., 3] > 0, 200, 0)
        root, sheet = self._sheet(soft, "soft.png")
        record = self.encode_textures.encode_sheet("soft_key", sheet, 32.0, root)
        self.assertFalse(record["encoded"])
        self.assertIn("soft alpha", record["reason"])

    def test_a_sheet_that_misses_the_quality_bar_is_declined_with_the_number(self) -> None:
        root, sheet = self._sheet(synthetic_sheet(64), "hard.png")
        record = self.encode_textures.encode_sheet("hard_key", sheet, 80.0, root)
        self.assertFalse(record["encoded"])
        self.assertIn("below the 80.00 dB bar", record["reason"])
        self.assertIsNotNone(record["psnrDb"])

    def test_a_sheet_that_clears_the_bar_is_encoded_and_measured(self) -> None:
        root, sheet = self._sheet(synthetic_sheet(64), "hard.png")
        record = self.encode_textures.encode_sheet("hard_key", sheet, 20.0, root)
        self.assertTrue(record["encoded"])
        self.assertEqual(record["encodedBytes"], 64 * 64 // 2)
        self.assertEqual(record["alphaAgreement"], 1.0)
        self.assertGreater(record["psnrDb"], 20.0)
